language: csharp
solution: Prismatic.sln
sudo: false

addons:
  apt:
    packages:
    - nunit-console

script:
 - xbuild /p:Configuration=Release Prismatic.sln
 - nunit-console ./Prismatic.Test/bin/Release/Prismatic.Test.dll
